[package]
name = "gchdb"
version = "0.2.5"
authors = ["DarkSky <darksky2048@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
keywords = ["chat", "database", "backup", "full-text"]
description = "Provides a record abstraction for storing chat records extracted by different chat software, and provides full-text search feature"
repository = "https://github.com/darkskygit/GCHDB"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.32"
cang-jie = "0.11.1"
chrono = "0.4.13"
futures = "0.3.5"
lazy_static = "1.4.0"
log = "0.4.11"
num_cpus = "1.13.0"
sha3 = "0.9.1"
thiserror = "1.0.20"

[dependencies.diesel]
version = "1.4.6"
features = ["chrono", "r2d2", "sqlite"]

[dependencies.diesel_migrations]
version = "1.4.0"

[dependencies.libsqlite3-sys]
version = "0.18.0"
features = ["bundled"]

[dependencies.serde]
version = "1.0.124"
features = ["derive"]

[dependencies.tantivy]
version = "0.14.0"
default-features = false
features = ["lz4-compression"]
