[package]
name = "common_chat_record"
version = "0.1.0"
authors = ["DarkSky <darksky2048@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.30"
chrono = "0.4.11"
thiserror = "1.0.17"

[dependencies.diesel]
version = "1.4.4"
features = ["chrono", "r2d2", "sqlite"]

[dependencies.diesel_migrations]
version = "1.4.0"

[dependencies.libsqlite3-sys]
version = "0.17.3"
features = ["bundled"]

[dependencies.serde]
version = "1.0.110"
features = ["derive"]
