[package]
name = "gchdb"
version = "0.2.9"
authors = ["DarkSky <darksky2048@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
keywords = ["chat", "database", "backup", "full-text"]
description = "Provides a record abstraction for storing chat records extracted by different chat software, and provides full-text search feature"
repository = "https://github.com/darkskygit/GCHDB"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.92"
chrono = "0.4.38"
diesel = { version = "2.2.4", features = ["chrono", "r2d2", "sqlite"] }
diesel_migrations = "2.2.0"
futures = "0.3.31"
lazy_static = "1.5.0"
libsqlite3-sys = { version = "0.30.1", features = ["bundled"] }
log = "0.4.22"
num_cpus = "1.16.0"
sha3 = "0.10.8"

cang-jie = { workspace = true }
serde = { workspace = true }
tantivy = { workspace = true }
thiserror = { workspace = true }
